#!/bin/bash

# RUN THIS SCRIPT AS ROOT
# Warning: changing the values of the variables in this script may render it unworkable.

BRANCH=main-x86_64

# The values below refer to the installation directories. If needed to change them,
# do it cautiously.
PROGRAM_DIR=/usr/share/update-hosts-file
EXEC_DIR=/usr/bin
MODULES_DIR=$PROGRAM_DIR/modules
CUSTOM_MODULES_DIR=$MODULES_DIR/custom
WEB_MODULES_DIR=$MODULES_DIR/web
CONFIG_DIR=$PROGRAM_DIR/config
BACKUP_DIR=$PROGRAM_DIR/backup
HOSTS_FILE=/etc/hosts

# Shell display functions
show_info(){
	echo "[  UpdateHostsFile  ] $1"
}

show_attention(){
	echo "[ ATTENTION ] $1"
}

finish_program()
{
	# $1 is the exit code
	exit $1
}

# Main functions
normal_installation()
{
	# Move executable to $EXEC_DIR
	cp bin/update-hosts-file $EXEC_DIR/update-hosts-file
	# Create program directory at $PROGRAM_DIR
	mkdir $PROGRAM_DIR
	# Move all files and directories remaining to $PROGRAM_DIR
	cp -R * $PROGRAM_DIR
	# Create remaining directories
	mkdir $PROGRAM_DIR/backup $PROGRAM_DIR/modules/web/enabled $PROGRAM_DIR/modules/custom/enabled
	# Enable default modules using hard links (available => enabled)
	show_info "Enabling Steven Black's hosts file web module"
	ln $PROGRAM_DIR/modules/web/available/stevenblack-fakenews-gambling-porn $PROGRAM_DIR/modules/web/enabled
	# Remove installation script
	rm $PROGRAM_DIR/install
	# Grant permissions
	grant_permissions
}

remove_old_program()
{
	rm -rf $PROGRAM_DIR
	if [ -f $EXEC_DIR/update-hosts-file ]
	then
		rm $EXEC_DIR/update-hosts-file
	else
		show_attention "Executable file not found. Make sure you removed it."
	fi
}

keep_custom_installation()
{
	if [ -d $MODULES_DIR ]
	then
		show_info "Modules directory found in $MODULES_DIR. Backing it up..."
		# Create a temporary directory
		TMP_DIR=/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
		mkdir $TMP_DIR
		# Remove modules directory downloaded
		#rm -rf modules
		# Backup current modules directory
		mv $MODULES_DIR $TMP_DIR/modules
		# And replace it with the current one
		#mv $MODULES_DIR .
	else
		show_attention "Modules directory not found in $MODULES_DIR."
		show_info "A new directory will be installed instead."
	fi

	if [ -f $CONFIG_DIR/preferences ]
	then
		show_info "Preferences file found in $CONFIG_DIR. Backing it up..."
		# Backup current preferences file
		mv $CONFIG_DIR/preferences $TMP_DIR/preferences
	else
		show_attention "Preferences file not found in $CONFIG_DIR"
		show_info "A new preferences file will be installed instead"
	fi
		
	# Remove old program
	remove_old_program
	# Move executable to $EXEC_DIR
	cp bin/update-hosts-file $EXEC_DIR/update-hosts-file
	# Create program directory at $PROGRAM_DIR
	mkdir $PROGRAM_DIR
	# Move all files and directories remaining to $PROGRAM_DIR
	cp -R * $PROGRAM_DIR
	# Substitute downloaded modules directory with the backed up one
	rm -rf $PROGRAM_DIR/modules
	if [ -d $TMP_DIR/modules ]
	then
		cp -R $TMP_DIR/modules $PROGRAM_DIR/modules
	fi
	# Substitute downloaded preferences file with backed up one
	rm -rf $CONFIG_DIR/preferences
	if [ -f $TMP_DIR/preferences ]
	then
		cp $TMP_DIR/preferences $CONFIG_DIR/preferences
	fi
	# Create remaining directories
	mkdir $PROGRAM_DIR/backup
	# Remove installation script
	rm $PROGRAM_DIR/install
	# Grant permissions
	grant_permissions
}

grant_permissions()
{
	# Change owner to root
	chown -R root:root $PROGRAM_DIR $EXEC_DIR/update-hosts-file
	# Change permissions bits for executables
	chmod -R 755 $EXEC_DIR/update-hosts-file $PROGRAM_DIR/bin $PROGRAM_DIR/install 2> /dev/null
	# Change permissions for directories
	chmod 755 $PROGRAM_DIR/backup $PROGRAM_DIR/config $PROGRAM_DIR/modules $PROGRAM_DIR/modules/custom $PROGRAM_DIR/modules/custom/available $PROGRAM_DIR/modules/custom/enabled $PROGRAM_DIR/modules/web $PROGRAM_DIR/modules/web/available $PROGRAM_DIR/modules/web/enabled 2> /dev/null
	# Change permissions bits for files inside directories (backup, config, custom)
	# and other files (LICENSE and README.md)
	chmod 644 $PROGRAM_DIR/backup/* $PROGRAM_DIR/config/* $PROGRAM_DIR/modules/custom/available/* $PROGRAM_DIR/modules/custom/enabled/* $PROGRAM_DIR/modules/web/available/* $PROGRAM_DIR/modules/web/enabled/* $PROGRAM_DIR/LICENSE $PROGRAM_DIR/README.md 2> /dev/null
}

#
##
#

show_info "Program files will be installed in $PROGRAM_DIR"
show_info "Executable will be installed in $EXEC_DIR"


if [ -d $PROGRAM_DIR ]
then
	show_info "Program directory already exists in $PROGRAM_DIR. If you continue, everything inside of it will be overwritten."

	echo ""

	show_info "Type 'keep' to keep your current modules directory located in $CUSTOM_MODULES_DIR and preferences file in $CONFIG_DIR/preferences."
	read KEEP_CUSTOM

	echo ""
	
	show_info "Type 'aware' to continue with the installation process. Any other character will automatically cancel it."
	read CONTINUE

	echo ""

	if [ ! "$CONTINUE" = 'aware' ]
	then
		show_attention "Aborting installation process"
		finish_program 1
	else
		show_info "Carrying on with the installation process"
		#remove_old_program
		#grant_permissions
		if [ "$KEEP_CUSTOM" = 'keep' ]
		then
			keep_custom_installation
		else
			remove_old_program
			normal_installation
		fi
	fi
else
	normal_installation
fi

# Finish program
show_info "Executable installed in $EXEC_DIR and configuration files in $PROGRAM_DIR"
# Remove temporary directory
rm -rf $TMP_DIR
finish_program 0
