#!/bin/bash

# GitHub repository: https://github.com/fearlessdots/update-hosts-file
# RUN THIS SCRIPT AS ROOT
# Warning: changing the values of the variables in this script may render it unworkable.

BRANCH=main-x86_64

# The values below refer to the installation directories. If needed to change them,
# do it cautiously.
PROGRAM_DIR=/usr/share/update-hosts-file
EXEC_DIR=/usr/bin

PROGRAM_DIR=/usr/share/update-hosts-file
MODULES_DIR=$PROGRAM_DIR/modules
CUSTOM_MODULES_DIR=$MODULES_DIR/custom
WEB_MODULES_DIR=$MODULES_DIR/web
CONFIG_DIR=$PROGRAM_DIR/config
BACKUP_DIR=$PROGRAM_DIR/backup
HOSTS_FILE=/etc/hosts

# Shell display functions
show_info(){
	echo "$1"
}

show_attention(){
	echo "[ ATTENTION ] $1"
}

finish_program()
{
	# $1 is the exit code
	exit $1
}

# Main functions
normal_installation()
{
	# Create remaining directories
	mkdir backup modules/web/available modules/custom/enabled
	# Grant permissions
	grant_permissions
	# Move executable to $EXEC_DIR
	mv bin/update-hosts-file $EXEC_DIR/update-hosts-file
	# Create program directory at $PROGRAM_DIR
	mkdir $PROGRAM_DIR
	# Remove this file
	rm ./install
	# Move all files and directories remaining to $PROGRAM_DIR
	mv * $PROGRAM_DIR
}

remove_old_program()
{
	rm -rf $PROGRAM_DIR
	if [ -f $EXEC_DIR/update-hosts-file ]
	then
		rm $EXEC_DIR/update-hosts-file
	else
		show_attention "Executable file not found. Make sure you removed it."
	fi
}

keep_modules_installation()
{
	if [ -d $MODULES_DIR ]
	then
		show_attention "Modules directory found in $MODULES_DIR. Backing it up..."
		# Remove modules directory downloaded
		rm -rf modules
		# And replace it with the current one
		mv $MODULES_DIR .
	else
		show_attention "Modules directory not found in $MODULES_DIR."
		show_attention "A new directory will be installed instead."
	fi

	remove_old_program

	# Grant permissions
	grant_permissions
	# Move executable to $EXEC_DIR
	mv bin/update-hosts-file $EXEC_DIR/update-hosts-file
	# Create program directory at $PROGRAM_DIR
	mkdir $PROGRAM_DIR
	# Remove this file
	rm ./install
	# Move all files and directories remaining to $PROGRAM_DIR
	mv * $PROGRAM_DIR
}

grant_permissions()
{
	# Change owner to root
	chown -R root:root *
	# Change permissions bits for executables
	chmod -R 755 bin install 2> /dev/null
	# Change permissions for directories
	chmod 755 backup config modules modules/custom modules/custom/available modules/custom/enabled modules/web modules/web/available modules/web/enabled 2> /dev/null
	# Change permissions bits for files inside directories (backup, config, custom)
	# and other files (LICENSE and README.md)
	chmod 644 backup/* config/* modules/custom/available/* modules/custom/enabled/* modules/web/available/* modules/web/enabled/* LICENSE README.md 2> /dev/null
}

#
##
#

show_info "Program files will be installed in $PROGRAM_DIR"
show_info "Executable will be installed in $EXEC_DIR"


if [ -d $PROGRAM_DIR ]
then
	show_info "Program directory already exists in $PROGRAM_DIR. If you continue, everything"
	show_info "inside it will be overwritten."
	show_info "Type 'keep' to keep your custom hosts modules located in $CUSTOM_HOSTS_DIR"
	read KEEP_MODULES
	show_info "Type 'aware' to continue with the installation process. Any other character will automatically cancel it."
	read CONTINUE
	if [ ! "$CONTINUE" = 'aware' ]
	then
		show_attention "Aborting installation process"
		finish_program 1
	else
		show_attention "Carrying on with the installation process"
		#remove_old_program
		#grant_permissions
		if [ "$KEEP_MODULES" = 'keep' ]
		then
			keep_modules_installation
		else
			remove_old_program
			normal_installation
		fi
	fi
else
	normal_installation
fi

show_info "Executable installed in $EXEC_DIR and configuration files in $PROGRAM_DIR"
show_info "The directory download should be empty now (if everything gone fine)."
finish_program 0
