#!/bin/bash

# RUN THIS SCRIPT AS ROOT
# Warning: changing the values of the variables in this script may render it unworkable.

BRANCH=main-x86_64

# The values below refer to the installation directories. If needed to change them,
# do it cautiously.
PROGRAM_DIR=/usr/share/update-hosts-file
EXEC_DIR=/usr/bin
MODULES_DIR=$PROGRAM_DIR/modules
CUSTOM_MODULES_DIR=$MODULES_DIR/custom
WEB_MODULES_DIR=$MODULES_DIR/web
CONFIG_DIR=$PROGRAM_DIR/config
BACKUP_DIR=$PROGRAM_DIR/backup
HOSTS_FILE=/etc/hosts
SYSMD_DIR=/usr/lib/systemd/system

# Shell display functions
show_info(){
	echo "$(tput setaf 25)[  UpdateHostsFile  ]$(tput sgr0) $(tput setaf 250)$1$(tput sgr0)"
}

show_attention()
{
	echo "$(tput setaf 9)[ ATTENTION ]$(tput sgr0) $(tput setaf 7)$1$(tput sgr0)"
}

show_success(){
	echo "$(tput setaf 14)[ SUCCESS ]$(tput sgr0) $(tput setaf 26)$1$(tput sgr0)"
}

finish_program()
{
	# $1 is the exit code
	exit $1
}

# Main functions
enable_stevenblack_module()
{
	show_info "Enabling $1 web module"
	ln "$PROGRAM_DIR/modules/web/available/$1" $PROGRAM_DIR/modules/web/enabled
}

normal_installation()
{
	# Move executable to $EXEC_DIR
	cp bin/update-hosts-file $EXEC_DIR/update-hosts-file
	# Create program directory at $PROGRAM_DIR
	mkdir $PROGRAM_DIR
	# Move all files and directories remaining to $PROGRAM_DIR
	cp -R * $PROGRAM_DIR
	# Create remaining directories
	mkdir $PROGRAM_DIR/backup $PROGRAM_DIR/modules/web/enabled $PROGRAM_DIR/modules/custom/enabled
	# Enable default modules using hard links (available => enabled)
	show_info """By default, there are 5 Steven Black web modules available. Choose one below:
1 - Unified Hosts
2 - Unified Hosts + Porn
3 - Unified Hosts + Porn + Gambling
4 - Unified Hosts + Porn + Gambling + Fake News
5 - Unified Hosts + Porn + Gambling + Fake News + Social
6 - skip: if you do not want to enable any Steven Black module right now."""

	while :
	do
		read OPTION
		if [ "$OPTION" = '1' ]
		then
			enable_stevenblack_module "stevenblack"
			break
		elif [ "$OPTION" = '2' ]
		then
			enable_stevenblack_module "stevenblack-porn"
			break
		elif [ "$OPTION" = '3' ]
		then
			enable_stevenblack_module "stevenblack-porn-gambling"
			break
		elif [ "$OPTION" = '4' ]
		then
			enable_stevenblack_module "stevenblack-porn-gambling-fakenews"
			break
		elif [ "$OPTION" = '5' ]
		then
			enable_stevenblack_module "stevenblack-porn-gambling-fakenews-social"
			break
		elif [ "$OPTION" = '6' ]
		then
			show_info "Skipping. You can enable/disable custom and web modules later by running 'update-hosts-file manage'."
			show_info "The 'default' module will be enabled to avoid letting the hosts file blank. Disable it whenever you enable any Steven Black module later to avoid duplicates."
			ln -s $PROGRAM_DIR/modules/custom/available/default $PROGRAM_DIR/modules/custom/enabled
			break
		else
			show_attention "Invalid option. Try again."
		fi
	done

	# Remove installation script
	rm $PROGRAM_DIR/install
	# Grant permissions
	grant_permissions
	# Move systemd service to the default SYSMD_DIR
	show_info "Copying systemd service to $SYSMD_DIR. If you want to enable it, run 'update-hosts-file enable'."
	cp updatehostsfile.service $SYSMD_DIR
}

remove_old_program()
{
	if [ -d $PROGRAM_DIR ]
	then
		rm -rf $PROGRAM_DIR
	else
		show_attention "Program directory not found. Make sure you removed it."
	fi
	
	if [ -f $EXEC_DIR/update-hosts-file ]
	then
		rm $EXEC_DIR/update-hosts-file
	else
		show_attention "Executable file not found. Make sure you removed it."
	fi
}

keep_custom_installation()
{
	if [ -d $MODULES_DIR ]
	then
		show_info "Modules directory found in $MODULES_DIR. Backing it up..."
		# Create a temporary directory
		TMP_DIR=/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
		mkdir $TMP_DIR
		# Backup current modules directory
		mv $MODULES_DIR $TMP_DIR/modules
	else
		show_attention "Modules directory not found in $MODULES_DIR."
		show_info "A new directory will be installed instead."
	fi

	if [ -f $CONFIG_DIR/preferences ]
	then
		show_info "Preferences file found in $CONFIG_DIR. Backing it up..."
		# Backup current preferences file
		mv $CONFIG_DIR/preferences $TMP_DIR/preferences
	else
		show_attention "Preferences file not found in $CONFIG_DIR"
		show_info "A new preferences file will be installed instead"
	fi
		
	# Remove old program
	remove_old_program
	# Move executable to $EXEC_DIR
	cp bin/update-hosts-file $EXEC_DIR/update-hosts-file
	# Create program directory at $PROGRAM_DIR
	mkdir $PROGRAM_DIR
	# Move all files and directories remaining to $PROGRAM_DIR
	cp -R * $PROGRAM_DIR
	# Substitute downloaded modules directory with the backed up one
	rm -rf $PROGRAM_DIR/modules
	if [ -d $TMP_DIR/modules ]
	then
		cp -R $TMP_DIR/modules $PROGRAM_DIR/modules
	fi
	# Substitute downloaded preferences file with backed up one
	rm -rf $CONFIG_DIR/preferences
	if [ -f $TMP_DIR/preferences ]
	then
		cp $TMP_DIR/preferences $CONFIG_DIR/preferences
	fi
	# Create remaining directories
	mkdir $PROGRAM_DIR/backup
	# Remove installation script
	rm $PROGRAM_DIR/install
	# Grant permissions
	grant_permissions
}

grant_permissions()
{
	# Change owner to root
	chown -R root:root $PROGRAM_DIR $EXEC_DIR/update-hosts-file
	# Change permissions bits for executables
	chmod -R 755 $EXEC_DIR/update-hosts-file $PROGRAM_DIR/bin $PROGRAM_DIR/install 2> /dev/null
	# Change permissions for directories
	chmod 755 $PROGRAM_DIR/backup $PROGRAM_DIR/config $PROGRAM_DIR/modules $PROGRAM_DIR/modules/custom $PROGRAM_DIR/modules/custom/available $PROGRAM_DIR/modules/custom/enabled $PROGRAM_DIR/modules/web $PROGRAM_DIR/modules/web/available $PROGRAM_DIR/modules/web/enabled 2> /dev/null
	# Change permissions bits for files inside directories (backup, config, custom)
	# and other files (LICENSE and README.md)
	chmod 644 $PROGRAM_DIR/backup/* $PROGRAM_DIR/config/* $PROGRAM_DIR/modules/custom/available/* $PROGRAM_DIR/modules/custom/enabled/* $PROGRAM_DIR/modules/web/available/* $PROGRAM_DIR/modules/web/enabled/* $PROGRAM_DIR/LICENSE $PROGRAM_DIR/README.md 2> /dev/null
}

#
##
#

show_info "Program files will be installed in $PROGRAM_DIR"
show_info "Executable will be installed in $EXEC_DIR"


if [ -d $PROGRAM_DIR ]
then
	show_info "Program directory already exists in $PROGRAM_DIR. If you continue, everything inside of it will be overwritten."

	echo ""

	show_info "Type 'keep' to keep your current modules directory located in $CUSTOM_MODULES_DIR and preferences file in $CONFIG_DIR/preferences."
	read KEEP_CUSTOM

	echo ""
	
	show_info "Type 'aware' to continue with the installation process. Any other character will automatically cancel it."
	read CONTINUE

	echo ""

	if [ ! "$CONTINUE" = 'aware' ]
	then
		show_attention "Aborting installation process"
		finish_program 1
	else
		show_info "Carrying on with the installation process"
		#grant_permissions
		if [ "$KEEP_CUSTOM" = 'keep' ]
		then
			keep_custom_installation
		else
			remove_old_program
			normal_installation
		fi
	fi
else
	normal_installation
fi

# Finish program
show_success "Program installed succesfully!"
# Remove temporary directory
rm -rf $TMP_DIR
finish_program 0
